DROP TABLE IF EXISTS dado;
DROP TABLE IF EXISTS juego;
DROP TABLE IF EXISTS jugador;

CREATE TABLE jugador (
	id_jugador INTEGER NOT NULL AUTO_INCREMENT,
	fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	nombre VARCHAR(250) NOT NULL,
	ratio DECIMAL NOT NULL DEFAULT(0.0),
	PRIMARY KEY (id_jugador)
);

CREATE TABLE dado (
	id_dado INTEGER NOT NULL AUTO_INCREMENT,
	id_jugador INTEGER NOT NULL,
	dado1 SMALLINT NOT NULL,
	dado2 SMALLINT NOT NULL,
	resultado SMALLINT NOT NULL,
	PRIMARY KEY (id_dado),
	FOREIGN KEY (id_jugador) REFERENCES jugador(id_jugador) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE juego (
	id_juego INTEGER NOT NULL AUTO_INCREMENT,
	id_jugador INTEGER NOT NULL,
	id_dado INTEGER NOT NULL,
	resultado BOOLEAN NOT NULL,
	PRIMARY KEY (id_juego),
	FOREIGN KEY (id_jugador) REFERENCES jugador(id_jugador) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (id_dado) REFERENCES dado(id_dado) ON DELETE SET NULL ON UPDATE CASCADE
);